### ISSUE TITLE
タイル数のリクエスト

### ISSUE THREAD

**Issue by nosigner** [MIERUNE/ElevationTile4JP#28]
大変ありがたく使わせてもらっております。ありがとうございます。
タイル数についてのリクエストなのですが、
100枚だとせっかくXYZタイルで大きく取得できるメリットが活かせずに、
ときには何十枚も結合して使っております。

たとえば1000枚くらいまで許容してもらえると大変使いやすくなるのですが、
ご検討いただくことは可能でしょうか？

**Comment by bordoray** [comment]
次のリリースで1000枚まで対応で可能です。

**Comment by bordoray** [comment]
Solved with v1.1 release.
