### ISSUE TITLE
データDL量が多い場合の対処法

### ISSUE THREAD

**Issue by Yfuruchin** [MIERUNE/ElevationTile4JP#3]
- 現状
	- z14などでタイルを行うと、データ量が大きすぎますと表示されてプラグインが停止
- 対応案
	- 範囲指定時に警告を出す
	- ゆっくりでもプログレスバーを出す

**Comment by bordoray** [comment]
Memo : 
https://github.com/MIERUNE/ElevationTile4JP/blob/master/get_tiles.py#L111
Convert to message box.

Should : Show message with threshold

**Comment by bordoray** [comment]
Related issue 
https://github.com/MIERUNE/ElevationTile4JP/issues/28

**Comment by bordoray** [comment]
> 範囲指定時に警告を出す

Solved with #36 

> ゆっくりでもプログレスバーを出す

To be done with issue #34
